git clean -dfX
cmake . -DWITHOUT_OQGRAPH_STORAGE_ENGINE=1 -DWITHOUT_TOKUDB_STORAGE_ENGINE=1 -DWITH_EMBEDDED_SERVER=1 -DWITHOUT_MROONGA_STORAGE_ENGINE=1 -DWITHOUT_SPIDER_STORAGE_ENGINE=1 -DWITHOUT_ROCKSDB_STORAGE_ENGINE=1 -DCMAKE_BUILD_TYPE=Debug
make -j8

